var ironclad_common = ["Images/Cards/Ironclad/Common/Anger.webp",  "Images/Cards/Ironclad/Common/Armaments.webp",  "Images/Cards/Ironclad/Common/Bash.webp",  "Images/Cards/Ironclad/Common/BodySlam.webp",  "Images/Cards/Ironclad/Common/Clash.webp",  "Images/Cards/Ironclad/Common/Cleave.webp",  "Images/Cards/Ironclad/Common/Clothesline.webp",  "Images/Cards/Ironclad/Common/Defend_R.webp",  "Images/Cards/Ironclad/Common/Flex.webp",  "Images/Cards/Ironclad/Common/Havoc.webp",  "Images/Cards/Ironclad/Common/Headbutt.webp",  "Images/Cards/Ironclad/Common/HeavyBlade.webp",  "Images/Cards/Ironclad/Common/IronWave.webp",  "Images/Cards/Ironclad/Common/PerfectedStrike.webp",  "Images/Cards/Ironclad/Common/PommelStrike.webp",  "Images/Cards/Ironclad/Common/ShrugItOff.webp",  "Images/Cards/Ironclad/Common/Strike_R.webp",  "Images/Cards/Ironclad/Common/SwordBoomerang.webp",  "Images/Cards/Ironclad/Common/Thunderclap.webp",  "Images/Cards/Ironclad/Common/TrueGrit.webp",  "Images/Cards/Ironclad/Common/TwinStrike.webp",  "Images/Cards/Ironclad/Common/Warcry.webp",  "Images/Cards/Ironclad/Common/WildStrike.webp"];
var ironclad_uncommon = ["Images/Cards/Ironclad/Uncommon/BattleTrance.webp", "Images/Cards/Ironclad/Uncommon/BloodforBloodwebp.webp", "Images/Cards/Ironclad/Uncommon/Bloodletting.webp", "Images/Cards/Ironclad/Uncommon/BurningPact.webp", "Images/Cards/Ironclad/Uncommon/Carnage.webp", "Images/Cards/Ironclad/Uncommon/Combust.webp", "Images/Cards/Ironclad/Uncommon/DarkEmbrace.webp", "Images/Cards/Ironclad/Uncommon/Disarm.webp", "Images/Cards/Ironclad/Uncommon/Dropkick.webp", "Images/Cards/Ironclad/Uncommon/DualWield.webp", "Images/Cards/Ironclad/Uncommon/Entrench.webp", "Images/Cards/Ironclad/Uncommon/Evolve.webp", "Images/Cards/Ironclad/Uncommon/FeelNoPain.webp", "Images/Cards/Ironclad/Uncommon/FireBreathing.webp", "Images/Cards/Ironclad/Uncommon/FlameBarrier.webp", "Images/Cards/Ironclad/Uncommon/GhostlyArmor.webp", "Images/Cards/Ironclad/Uncommon/Hemokinesis.webp", "Images/Cards/Ironclad/Uncommon/InfernalBlade.webp", "Images/Cards/Ironclad/Uncommon/Inflame.webp", "Images/Cards/Ironclad/Uncommon/Intimidate.webp", "Images/Cards/Ironclad/Uncommon/Metallicize.webp", "Images/Cards/Ironclad/Uncommon/PowerThrough.webp", "Images/Cards/Ironclad/Uncommon/Pummel.webp", "Images/Cards/Ironclad/Uncommon/Rage.webp", "Images/Cards/Ironclad/Uncommon/Rampage.webp", "Images/Cards/Ironclad/Uncommon/RecklessCharge.webp", "Images/Cards/Ironclad/Uncommon/Rupture.webp", "Images/Cards/Ironclad/Uncommon/SearingBlow.webp", "Images/Cards/Ironclad/Uncommon/SecondWind.webp", "Images/Cards/Ironclad/Uncommon/SeeingRed.webp", "Images/Cards/Ironclad/Uncommon/Sentinel.webp", "Images/Cards/Ironclad/Uncommon/SeverSoul.webp", "Images/Cards/Ironclad/Uncommon/Shockwave.webp", "Images/Cards/Ironclad/Uncommon/SpotWeakness.webp", "Images/Cards/Ironclad/Uncommon/Uppercut.webp", "Images/Cards/Ironclad/Uncommon/Whirlwind.webp"];
var ironclad_rare = ["Images/Cards/Ironclad/Rare/Barricade.webp", "Images/Cards/Ironclad/Rare/Berserk.webp", "Images/Cards/Ironclad/Rare/Bludgeon.webp", "Images/Cards/Ironclad/Rare/Brutality.webp", "Images/Cards/Ironclad/Rare/Corruption.webp", "Images/Cards/Ironclad/Rare/DemonForm.webp", "Images/Cards/Ironclad/Rare/DoubleTap.webp", "Images/Cards/Ironclad/Rare/Exhume.webp", "Images/Cards/Ironclad/Rare/Feed.webp", "Images/Cards/Ironclad/Rare/FiendFire.webp", "Images/Cards/Ironclad/Rare/Immolate.webp", "Images/Cards/Ironclad/Rare/Impervious.webp", "Images/Cards/Ironclad/Rare/Juggernaut.webp", "Images/Cards/Ironclad/Rare/LimitBreak.webp", "Images/Cards/Ironclad/Rare/Offering.webp", "Images/Cards/Ironclad/Rare/Reaper.webp"];

var silent_common = ["Images/Cards/Silent/Common/Acrobatics.webp", "Images/Cards/Silent/Common/Backflip.webp", "Images/Cards/Silent/Common/Bane.webp", "Images/Cards/Silent/Common/BladeDance.webp", "Images/Cards/Silent/Common/CloakAndDagger.webp", "Images/Cards/Silent/Common/DaggerSpray.webp", "Images/Cards/Silent/Common/DeadlyPoison.webp", "Images/Cards/Silent/Common/Defend_G.webp", "Images/Cards/Silent/Common/Deflect.webp", "Images/Cards/Silent/Common/DodgeandRoll.webp", "Images/Cards/Silent/Common/FlyingKnee.webp", "Images/Cards/Silent/Common/Neutralize.webp", "Images/Cards/Silent/Common/Outmaneuver.webp", "Images/Cards/Silent/Common/PiercingWail.webp", "Images/Cards/Silent/Common/PoisonedStab.webp", "Images/Cards/Silent/Common/Prepared.webp", "Images/Cards/Silent/Common/QuickSlash.webp", "Images/Cards/Silent/Common/R_dagger-throw.webp", "Images/Cards/Silent/Common/Shiv.webp", "Images/Cards/Silent/Common/Slice.webp", "Images/Cards/Silent/Common/SneakyStrike.webp", "Images/Cards/Silent/Common/Strike_G.webp", "Images/Cards/Silent/Common/SuckerPunch.webp", "Images/Cards/Silent/Common/Survivor.webp"];
var silent_uncommon = ["Images/Cards/Silent/Uncommon/Accuracy.webp", "Images/Cards/Silent/Uncommon/All-OutAttack.webp", "Images/Cards/Silent/Uncommon/Backstab.webp", "Images/Cards/Silent/Uncommon/Blur.webp", "Images/Cards/Silent/Uncommon/BouncingFlask.webp", "Images/Cards/Silent/Uncommon/CalculatedGamble.webp", "Images/Cards/Silent/Uncommon/Caltrops.webp", "Images/Cards/Silent/Uncommon/Catalyst.webp", "Images/Cards/Silent/Uncommon/Choke.webp", "Images/Cards/Silent/Uncommon/Concentrate.webp", "Images/Cards/Silent/Uncommon/CripplingCloud.webp", "Images/Cards/Silent/Uncommon/Dash.webp", "Images/Cards/Silent/Uncommon/Distraction.webp", "Images/Cards/Silent/Uncommon/EndlessAgony.webp", "Images/Cards/Silent/Uncommon/EscapePlan.webp", "Images/Cards/Silent/Uncommon/Eviscerate.webp", "Images/Cards/Silent/Uncommon/Expertise.webp", "Images/Cards/Silent/Uncommon/Finisher.webp", "Images/Cards/Silent/Uncommon/Flechettes.webp", "Images/Cards/Silent/Uncommon/Footwork.webp", "Images/Cards/Silent/Uncommon/HeelHook.webp", "Images/Cards/Silent/Uncommon/InfiniteBlades.webp", "Images/Cards/Silent/Uncommon/LegSweep.webp", "Images/Cards/Silent/Uncommon/MasterfulStab.webp", "Images/Cards/Silent/Uncommon/NoxiousFumes.webp", "Images/Cards/Silent/Uncommon/Predator.webp", "Images/Cards/Silent/Uncommon/Reflex.webp", "Images/Cards/Silent/Uncommon/RiddleWithHoles.webp", "Images/Cards/Silent/Uncommon/Setup.webp", "Images/Cards/Silent/Uncommon/Skewer.webp", "Images/Cards/Silent/Uncommon/Tactician.webp", "Images/Cards/Silent/Uncommon/Terror.webp", "Images/Cards/Silent/Uncommon/Well-LaidPlans.webp"];
var silent_rare = ["Images/Cards/Silent/Rare/Adrenaline.webp", "Images/Cards/Silent/Rare/AfterImage.webp", "Images/Cards/Silent/Rare/Alchemize.webp", "Images/Cards/Silent/Rare/AThousandCuts.webp", "Images/Cards/Silent/Rare/BulletTime.webp", "Images/Cards/Silent/Rare/Burst.webp", "Images/Cards/Silent/Rare/CorpseExplosion.webp", "Images/Cards/Silent/Rare/DieDieDie.webp", "Images/Cards/Silent/Rare/Doppelganger.webp", "Images/Cards/Silent/Rare/Envenom.webp", "Images/Cards/Silent/Rare/GlassKnife.webp", "Images/Cards/Silent/Rare/GrandFinale.webp", "Images/Cards/Silent/Rare/Malaise.webp", "Images/Cards/Silent/Rare/Nightmare.webp", "Images/Cards/Silent/Rare/PhantasmalKiller.webp", "Images/Cards/Silent/Rare/StormofSteel.webp", "Images/Cards/Silent/Rare/ToolsoftheTrade.webp", "Images/Cards/Silent/Rare/Unload.webp", "Images/Cards/Silent/Rare/WraithForm.webp"];

var defect_common = ["Images/Cards/Defect/Common/BallLightning.webp", "Images/Cards/Defect/Common/Barrage.webp", "Images/Cards/Defect/Common/BeamCell.webp", "Images/Cards/Defect/Common/ChargeBattery.webp", "Images/Cards/Defect/Common/Claw.webp", "Images/Cards/Defect/Common/ColdSnap.webp", "Images/Cards/Defect/Common/CompileDriver.webp", "Images/Cards/Defect/Common/Coolheaded.webp", "Images/Cards/Defect/Common/Defend_B.webp", "Images/Cards/Defect/Common/Dualcast.webp", "Images/Cards/Defect/Common/GofortheEyes.webp", "Images/Cards/Defect/Common/Hologram-0.webp", "Images/Cards/Defect/Common/Leap.webp", "Images/Cards/Defect/Common/Rebound.webp", "Images/Cards/Defect/Common/Recursion.webp", "Images/Cards/Defect/Common/Stack.webp", "Images/Cards/Defect/Common/SteamBarrier.webp", "Images/Cards/Defect/Common/Streamline.webp", "Images/Cards/Defect/Common/Strike_B.webp", "Images/Cards/Defect/Common/SweepingBeam.webp", "Images/Cards/Defect/Common/TURBO.webp", "Images/Cards/Defect/Common/Zap.webp"];
var defect_uncommon = ["Images/Cards/Defect/Uncommon/Aggregate.webp", "Images/Cards/Defect/Uncommon/Auto-Shields.webp", "Images/Cards/Defect/Uncommon/Blizzard.webp", "Images/Cards/Defect/Uncommon/BootSequence.webp", "Images/Cards/Defect/Uncommon/BullsEye.webp", "Images/Cards/Defect/Uncommon/Capacitor.webp", "Images/Cards/Defect/Uncommon/Chaos.webp", "Images/Cards/Defect/Uncommon/Chill.webp", "Images/Cards/Defect/Uncommon/Consume.webp", "Images/Cards/Defect/Uncommon/Darkness.webp", "Images/Cards/Defect/Uncommon/Defragment.webp", "Images/Cards/Defect/Uncommon/DoomandGloom.webp", "Images/Cards/Defect/Uncommon/DoubleEnergy.webp", "Images/Cards/Defect/Uncommon/Equilibrium.webp", "Images/Cards/Defect/Uncommon/ForceField.webp", "Images/Cards/Defect/Uncommon/FTL.webp", "Images/Cards/Defect/Uncommon/Fusion.webp", "Images/Cards/Defect/Uncommon/GeneticAlgorithm.webp", "Images/Cards/Defect/Uncommon/Glacier.webp", "Images/Cards/Defect/Uncommon/Heatsinks.webp", "Images/Cards/Defect/Uncommon/HelloWorld.webp", "Images/Cards/Defect/Uncommon/Loop.webp", "Images/Cards/Defect/Uncommon/Melter.webp", "Images/Cards/Defect/Uncommon/Overclock.webp", "Images/Cards/Defect/Uncommon/Recycle.webp", "Images/Cards/Defect/Uncommon/ReinforcedBody.webp", "Images/Cards/Defect/Uncommon/Reprogram.webp", "Images/Cards/Defect/Uncommon/RipandTear.webp", "Images/Cards/Defect/Uncommon/Scrape.webp", "Images/Cards/Defect/Uncommon/SelfRepair.webp", "Images/Cards/Defect/Uncommon/Skim.webp", "Images/Cards/Defect/Uncommon/StaticDischarge.webp", "Images/Cards/Defect/Uncommon/Storm.webp", "Images/Cards/Defect/Uncommon/Sunder.webp", "Images/Cards/Defect/Uncommon/Tempest.webp", "Images/Cards/Defect/Uncommon/WhiteNoise.webp"];
var defect_rare = ["Images/Cards/Defect/Rare/AllforOne.webp", "Images/Cards/Defect/Rare/Amplify.webp", "Images/Cards/Defect/Rare/BiasedCognition.webp", "Images/Cards/Defect/Rare/Buffer.webp", "Images/Cards/Defect/Rare/CoreSurge.webp", "Images/Cards/Defect/Rare/CreativeAI.webp", "Images/Cards/Defect/Rare/EchoForm.webp", "Images/Cards/Defect/Rare/Electrodynamics.webp", "Images/Cards/Defect/Rare/Fission.webp", "Images/Cards/Defect/Rare/Hyperbeam.webp", "Images/Cards/Defect/Rare/MachineLearning.webp", "Images/Cards/Defect/Rare/MeteorStrike.webp", "Images/Cards/Defect/Rare/Multi-Cast.webp", "Images/Cards/Defect/Rare/Rainbow.webp", "Images/Cards/Defect/Rare/Reboot.webp", "Images/Cards/Defect/Rare/Seek.webp", "Images/Cards/Defect/Rare/ThunderStrike.webp"];

var watcher_common = ["Images/Cards/Watcher/Common/BowlingBash.webp", "Images/Cards/Watcher/Common/Consecrate.webp", "Images/Cards/Watcher/Common/Crescendo.webp", "Images/Cards/Watcher/Common/CrushJoints.webp", "Images/Cards/Watcher/Common/CutThroughFate.webp", "Images/Cards/Watcher/Common/Defend_P.webp", "Images/Cards/Watcher/Common/EmptyBody.webp", "Images/Cards/Watcher/Common/EmptyFist.webp", "Images/Cards/Watcher/Common/Eruption.webp", "Images/Cards/Watcher/Common/Evaluate.webp", "Images/Cards/Watcher/Common/FlurryOfBlows.webp", "Images/Cards/Watcher/Common/FlyingSleeves.webp", "Images/Cards/Watcher/Common/Follow-Up.webp", "Images/Cards/Watcher/Common/Halt.webp", "Images/Cards/Watcher/Common/Insight.webp", "Images/Cards/Watcher/Common/JustLucky.webp", "Images/Cards/Watcher/Common/Miracle.webp", "Images/Cards/Watcher/Common/PressurePoints.webp", "Images/Cards/Watcher/Common/Prostrate.webp", "Images/Cards/Watcher/Common/Protect.webp", "Images/Cards/Watcher/Common/SashWhip.webp", "Images/Cards/Watcher/Common/Strike_P.webp", "Images/Cards/Watcher/Common/ThirdEye.webp", "Images/Cards/Watcher/Common/Tranquility.webp", "Images/Cards/Watcher/Common/Vigilance.webp"];
var watcher_uncommon = ["Images/Cards/Watcher/Uncommon/BattleHymn.webp", "Images/Cards/Watcher/Uncommon/CarveReality.webp", "Images/Cards/Watcher/Uncommon/Collect.webp", "Images/Cards/Watcher/Uncommon/Conclude.webp", "Images/Cards/Watcher/Uncommon/DeceiveReality.webp", "Images/Cards/Watcher/Uncommon/EmptyMind.webp", "Images/Cards/Watcher/Uncommon/Fasting.webp", "Images/Cards/Watcher/Uncommon/FearNoEvil.webp", "Images/Cards/Watcher/Uncommon/ForeignInfluence.webp", "Images/Cards/Watcher/Uncommon/Foresight.webp", "Images/Cards/Watcher/Uncommon/Indignation.webp", "Images/Cards/Watcher/Uncommon/InnerPeace.webp", "Images/Cards/Watcher/Uncommon/LikeWater.webp", "Images/Cards/Watcher/Uncommon/Meditate.webp", "Images/Cards/Watcher/Uncommon/MentalFortress.webp", "Images/Cards/Watcher/Uncommon/Nirvana.webp", "Images/Cards/Watcher/Uncommon/Perseverance.webp", "Images/Cards/Watcher/Uncommon/Pray.webp", "Images/Cards/Watcher/Uncommon/ReachHeaven.webp", "Images/Cards/Watcher/Uncommon/Rushdown.webp", "Images/Cards/Watcher/Uncommon/Safety.webp", "Images/Cards/Watcher/Uncommon/Sanctity.webp", "Images/Cards/Watcher/Uncommon/SandsofTime.webp", "Images/Cards/Watcher/Uncommon/SignatureMove.webp", "Images/Cards/Watcher/Uncommon/SimmeringFury.webp", "Images/Cards/Watcher/Uncommon/Smite.webp", "Images/Cards/Watcher/Uncommon/Study.webp", "Images/Cards/Watcher/Uncommon/Swivel.webp", "Images/Cards/Watcher/Uncommon/TalktotheHand.webp", "Images/Cards/Watcher/Uncommon/Tantrum.webp", "Images/Cards/Watcher/Uncommon/ThroughViolence.webp", "Images/Cards/Watcher/Uncommon/Wallop.webp", "Images/Cards/Watcher/Uncommon/WaveoftheHand.webp", "Images/Cards/Watcher/Uncommon/Weave.webp", "Images/Cards/Watcher/Uncommon/WheelKick.webp", "Images/Cards/Watcher/Uncommon/WindmillStrike.webp", "Images/Cards/Watcher/Uncommon/Worship.webp", "Images/Cards/Watcher/Uncommon/WreathofFlame.webp"];
var watcher_rare = ["Images/Cards/Watcher/Rare/Alpha.webp", "Images/Cards/Watcher/Rare/Beta.webp", "Images/Cards/Watcher/Rare/Blasphemy.webp", "Images/Cards/Watcher/Rare/Brilliance.webp", "Images/Cards/Watcher/Rare/ConjureBlade.webp", "Images/Cards/Watcher/Rare/DeusExMachina.webp", "Images/Cards/Watcher/Rare/DevaForm.webp", "Images/Cards/Watcher/Rare/Devotion.webp", "Images/Cards/Watcher/Rare/Establishment.webp", "Images/Cards/Watcher/Rare/Expunger.webp", "Images/Cards/Watcher/Rare/Judgment.webp", "Images/Cards/Watcher/Rare/LessonLearned.webp", "Images/Cards/Watcher/Rare/MasterReality.webp", "Images/Cards/Watcher/Rare/Omega.webp", "Images/Cards/Watcher/Rare/Omniscience.webp", "Images/Cards/Watcher/Rare/Ragnarok.webp", "Images/Cards/Watcher/Rare/Scrawl.webp", "Images/Cards/Watcher/Rare/SpiritShield.webp", "Images/Cards/Watcher/Rare/Vault.webp", "Images/Cards/Watcher/Rare/Wish.webp"];

var curse = ["Images/Cards/Curse/Ascenders_Bane.webp", "Images/Cards/Curse/Clumsy.webp", "Images/Cards/Curse/CurseoftheBell.webp", "Images/Cards/Curse/Decay.webp", "Images/Cards/Curse/Doubt.webp", "Images/Cards/Curse/Injury.webp", "Images/Cards/Curse/Necronomicurse.webp", "Images/Cards/Curse/Normality.webp", "Images/Cards/Curse/Pain.webp", "Images/Cards/Curse/Parasite.webp", "Images/Cards/Curse/Pride.webp", "Images/Cards/Curse/Regret.webp", "Images/Cards/Curse/Shame.webp", "Images/Cards/Curse/Writhe.webp"];
var status = ["Images/Cards/Status/Burn.webp", "Images/Cards/Status/Dazed.webp", "Images/Cards/Status/Slimed.webp", "Images/Cards/Status/Void.webp", "Images/Cards/Status/Wound.webp"];
var colorless = ["Images/Cards/Colorless/Apotheosis.webp", "Images/Cards/Colorless/Apparition.webp", "Images/Cards/Colorless/BandageUp.webp", "Images/Cards/Colorless/Bite.webp", "Images/Cards/Colorless/Blind.webp", "Images/Cards/Colorless/Chrysalis.webp", "Images/Cards/Colorless/DarkShackles.webp", "Images/Cards/Colorless/DeepBreath.webp", "Images/Cards/Colorless/Discovery.webp", "Images/Cards/Colorless/DramaticEntrance.webp", "Images/Cards/Colorless/Enlightenment.webp", "Images/Cards/Colorless/Finesse.webp", "Images/Cards/Colorless/FlashofSteel.webp", "Images/Cards/Colorless/Forethought.webp", "Images/Cards/Colorless/GoodInstincts.webp", "Images/Cards/Colorless/HandOfGreed.webp", "Images/Cards/Colorless/Impatience.webp", "Images/Cards/Colorless/J.A.X..webp", "Images/Cards/Colorless/JackOfAllTrades.webp", "Images/Cards/Colorless/Madness.webp", "Images/Cards/Colorless/Magnetism.webp", "Images/Cards/Colorless/MasterOfStrategy.webp", "Images/Cards/Colorless/Mayhem.webp", "Images/Cards/Colorless/Metamorphosis.webp", "Images/Cards/Colorless/MindBlast.webp", "Images/Cards/Colorless/Panacea.webp", "Images/Cards/Colorless/Panache.webp", "Images/Cards/Colorless/PanicButton.webp", "Images/Cards/Colorless/Purity.webp", "Images/Cards/Colorless/RitualDagger.webp", "Images/Cards/Colorless/SadisticNature.webp", "Images/Cards/Colorless/SecretTechnique.webp", "Images/Cards/Colorless/SecretWeapon.webp", "Images/Cards/Colorless/SwiftStrike.webp", "Images/Cards/Colorless/TheBomb.webp", "Images/Cards/Colorless/ThinkingAhead.webp", "Images/Cards/Colorless/Transmutation.webp", "Images/Cards/Colorless/Trip.webp", "Images/Cards/Colorless/Violence.webp"];

function losowanie_common() {
    var liczba = Math.floor(Math.random() * (ironclad_common.length));
    document.common.src=""+ironclad_common[liczba];
}

function losowanie_uncommon() {
    var liczba = Math.floor(Math.random() * (ironclad_uncommon.length));
    document.uncommon.src=""+ironclad_uncommon[liczba];
}

function losowanie_rare() {
    var liczba = Math.floor(Math.random() * (ironclad_rare.length));
    document.rare.src=""+ironclad_rare[liczba];
}
